include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_return_types_on_setters: true
    camel_case_types: true
    constant_identifier_names: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    use_key_in_widget_constructors: true
    prefer_relative_imports: true