name: crochetime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/