name: crochetime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Jomhuria
      fonts:
        - asset: assets/fonts/Jomhuria-Regular.ttf
  assets:
    - assets/images/